name: Frontend PR Pipeline

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  frontend-checks:
    name: Lint, Build e Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # OBRIGATÓRIO PARA O SONARCLOUD LER O PULL REQUEST

      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Check de Lint
        run: npm run lint

      - name: Check de Build
        run: npm run build

      - name: Check de Testes
        run: npm run test:coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info